# Generated by Django 5.1.1 on 2024-09-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_image', models.ImageField(blank=True, null=True, upload_to='payment_images/')),
                ('status', models.CharField(choices=[('S', 'Verified'), ('N', 'Not Verified')], default='N', max_length=1)),
                ('change_date', models.DateField(auto_now=True)),
                ('change_time', models.TimeField(auto_now=True)),
                ('psychological_appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.psychologicalappointment')),
            ],
        ),
    ]
