# Generated by Django 5.0.7 on 2024-08-12 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('patients', '0006_rename_id_company_patient_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('change_date', models.DateField(auto_now=True)),
                ('change_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('change_date', models.DateField(auto_now=True)),
                ('change_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('available', models.BooleanField(default=True)),
                ('change_date', models.DateField(auto_now=True)),
                ('change_time', models.TimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologicalAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Programada', max_length=15)),
                ('modality', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], default='P', max_length=1)),
                ('appointment_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.appointmentreason')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('schedule_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.scheduleblock')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.sede')),
            ],
        ),
    ]
