# Generated by Django 5.1.1 on 2024-09-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('modality', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual'), ('A', 'Ambos')], default='A', max_length=1)),
                ('change_date', models.DateField(auto_now=True)),
                ('change_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('enabled', models.BooleanField(default=True)),
                ('change_date', models.DateField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('duration', models.IntegerField()),
                ('change_date', models.DateField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaysEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('change_date', models.DateField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.day')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('change_date', models.DateField(auto_now=True)),
                ('change_time', models.TimeField(auto_now=True)),
                ('modality', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual'), ('A', 'Ambos')], default='A', max_length=1)),
                ('employees', models.ManyToManyField(related_name='sedes', to='employees.employee')),
                ('reasons', models.ManyToManyField(related_name='sedes', to='scheduling.appointmentreason')),
            ],
        ),
        migrations.CreateModel(
            name='PsychologicalAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Por validar pago', max_length=15)),
                ('modality', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], default='P', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointment_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.appointmentreason')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.sede')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.timeslot'),
        ),
    ]
