# Generated by Django 5.0.7 on 2024-08-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id_time', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('duration', models.IntegerField()),
                ('change_date', models.DateField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
