# Generated by Django 5.0.7 on 2024-08-25 05:09

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_psychologicalappointment_schedule_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalappointment',
            name='creation_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psychologicalappointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 25, 5, 5, 43, 34834, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psychologicalappointment',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 25, 5, 5, 47, 175983, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psychologicalappointment',
            name='days_employee',
            field=models.ForeignKey(default=124, on_delete=django.db.models.deletion.CASCADE, to='scheduling.daysemployee'),
            preserve_default=False,
        ),
    ]
