# Generated by Django 5.0.7 on 2024-09-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('scheduling', '0005_psychologicalappointment_creation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreason',
            name='modality',
            field=models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual'), ('A', 'Ambos')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='sede',
            name='employees',
            field=models.ManyToManyField(related_name='sedes', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='sede',
            name='modality',
            field=models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual'), ('A', 'Ambos')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='sede',
            name='reasons',
            field=models.ManyToManyField(related_name='sedes', to='scheduling.appointmentreason'),
        ),
    ]
