# Generated by Django 5.0.7 on 2024-09-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_appointmentreason_modality_sede_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalappointment',
            name='status',
            field=models.CharField(default='Pendiente de pago', max_length=15),
        ),
    ]
