# Generated by Django 5.0.7 on 2024-09-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_psychologicalappointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologicalappointment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
