# Generated by Django 5.0.7 on 2024-09-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_psychologicalappointment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologicalappointment',
            name='days_employee',
        ),
    ]
