# Generated by Django 5.0.7 on 2024-09-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_remove_psychologicalappointment_days_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalappointment',
            name='status',
            field=models.CharField(default='Por validar', max_length=15),
        ),
    ]
