# Generated by Django 5.0.7 on 2024-09-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_alter_psychologicalappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicalappointment',
            name='status',
            field=models.CharField(default='Por validar pago', max_length=15),
        ),
    ]
