# Generated by Django 5.1.1 on 2024-09-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, unique=True)),
                ('personal_history', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('physical_observations', models.TextField(blank=True, null=True)),
                ('behavioral_observations', models.TextField(blank=True, null=True)),
                ('personal_perception', models.TextField(blank=True, null=True)),
                ('academic_perception', models.TextField(blank=True, null=True)),
                ('habits', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('projections', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('sleep', models.TextField(blank=True, null=True)),
                ('nutrition', models.TextField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
