# Generated by Django 5.0.7 on 2024-08-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=18)),
            ],
            options={
                'db_table': 'tipoSeleccion',
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=25)),
                ('date_changed', models.DateField(auto_now_add=True)),
                ('time_changed', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tipoTest',
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.AddField(
            model_name='test',
            name='abbreviation',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='date_changed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='enabled',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='evaluation',
            field=models.CharField(default=None, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='max_age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='min_age',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='number_of_items',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='questionnaire',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='response',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='supervision',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='time_changed',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='test',
            table='Test',
        ),
        migrations.AddField(
            model_name='test',
            name='selection_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.selectiontype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.testtype'),
            preserve_default=False,
        ),
    ]
