# Generated by Django 5.0.7 on 2024-08-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_selectiontype_testtype_remove_test_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
    ]
