# Generated by Django 5.0.7 on 2024-08-11 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_test_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipoPregunta',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='date_changed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='time_changed',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='date_changed',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_changed',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='Respuesta',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Preguntas',
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('date_changed', models.DateField(auto_now=True)),
                ('time_changed', models.TimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='tests.test')),
            ],
            options={
                'db_table': 'Dimension',
            },
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('score', models.SmallIntegerField()),
                ('date_changed', models.DateField(auto_now=True)),
                ('time_changed', models.TimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='tests.dimension')),
            ],
            options={
                'db_table': 'Capacidades',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.questiontype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('start_range', models.CharField(max_length=2)),
                ('end_range', models.CharField(max_length=2)),
                ('result', models.SmallIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='tests.test')),
            ],
            options={
                'db_table': 'Escala',
            },
        ),
    ]
