# Generated by Django 5.0.7 on 2024-08-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_answer_id_alter_capacity_id_alter_dimension_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
                ('fechaCambio', models.DateField(auto_now_add=True)),
                ('horaCambio', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SelectionType',
            new_name='tipoSeleccion',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='capacity',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='scale',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='abbreviation',
            new_name='abreviatura',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='questionnaire',
            new_name='cuestionario',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='evaluation',
            new_name='evalua',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='enabled',
            new_name='habilitado',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test_name',
            new_name='nombreTest',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='response',
            new_name='respuesta',
        ),
        migrations.RenameField(
            model_name='tiposeleccion',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='date_changed',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='test',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='time_changed',
        ),
        migrations.RemoveField(
            model_name='test',
            name='date_changed',
        ),
        migrations.RemoveField(
            model_name='test',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='test',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='test',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='test',
            name='number_of_items',
        ),
        migrations.RemoveField(
            model_name='test',
            name='selection_type',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_changed',
        ),
        migrations.AddField(
            model_name='dimension',
            name='descripcion',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimension',
            name='fechaCambio',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimension',
            name='horaCambio',
            field=models.TimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimension',
            name='idTest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dimension',
            name='puntaje',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='duracion',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='edadMax',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='edadMin',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='fechaCambio',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='horaCambio',
            field=models.TimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='idSeleccion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests.tiposeleccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='nroItems',
            field=models.PositiveSmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='dimension',
            table=None,
        ),
        migrations.AlterModelTable(
            name='test',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tiposeleccion',
            table=None,
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('fechaCambio', models.DateField(auto_now_add=True)),
                ('horaCambio', models.TimeField(auto_now_add=True)),
                ('idTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
        ),
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCapacidad', models.CharField(max_length=25)),
                ('abreviatura', models.CharField(max_length=22)),
                ('puntaje', models.PositiveSmallIntegerField()),
                ('fechaCambio', models.DateField(auto_now_add=True)),
                ('horaCambio', models.TimeField(auto_now_add=True)),
                ('idDimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicioRango', models.PositiveSmallIntegerField()),
                ('finRango', models.PositiveSmallIntegerField()),
                ('resultado', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=10)),
                ('fechaCambio', models.DateField(auto_now_add=True)),
                ('horaCambio', models.TimeField(auto_now_add=True)),
                ('idDimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('fechaCambio', models.DateField(auto_now_add=True)),
                ('horaCambio', models.TimeField(auto_now_add=True)),
                ('idTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=10)),
                ('puntuacion', models.PositiveSmallIntegerField()),
                ('fechaCambio', models.DateField(auto_now_add=True)),
                ('horaCambio', models.TimeField(auto_now_add=True)),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='idTipoTest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tests.tipotest'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Capacity',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Scale',
        ),
        migrations.DeleteModel(
            name='TestType',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
