# Generated by Django 5.0.7 on 2024-07-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_dni_patient_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
