# Generated by Django 5.0.7 on 2024-08-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='legal_guardian',
        ),
        migrations.AlterField(
            model_name='patient',
            name='benefit',
            field=models.BooleanField(default=False),
        ),
    ]
