# Generated by Django 5.0.7 on 2024-08-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='id_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id_tutor',
            new_name='tutor',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id_user',
            new_name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
