# Generated by Django 5.0.7 on 2024-08-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='change_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='change_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
